# Generated by Django 4.1.5 on 2023-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
